title = "Takayuki Tominaga"
baseURL = "https://resume.tmng.me/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Yokohama, Kanagawa, Japan"
email = "contact.tmng@gmail.com"
favicon = "/favicon.ico"
firstName = "Takayuki"
lastName = "Tominaga"
phone = "(+81)-80-4284-1037"
profileImage = "img/profile.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = true


[[params.handles]]
link = "https://www.linkedin.com/in/takayuki-tominaga"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/touka-tt/"
name = "GitHub"

[[params.handles]]
link = "https://twitter.com/touka_tt"
name = "twitter"

[[params.handles]]
link = "https://www.facebook.com/takayuki.tominaga/"
name = "facebook"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"